# Generated by Django 3.1.7 on 2021-03-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0002_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity_ordered',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce_app.user')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce_app.product')),
            ],
        ),
    ]
