# Generated by Django 3.1.7 on 2021-03-31 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0004_remove_cart_price_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='description',
            new_name='item',
        ),
    ]
