# Generated by Django 3.1.7 on 2021-03-31 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0005_auto_20210331_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
