# Generated by Django 3.1.7 on 2021-04-01 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0007_auto_20210331_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce_app.cart'),
        ),
    ]
